In [ ]:
import open3d as o3d
import numpy as np

# 1. Extrinsic 행렬
extrinsic = np.array([
    [9.99989767e-01, -4.90776873e-04, -4.49909066e-03, 0.00000000e+00],
    [4.73515341e-04,  9.99992554e-01, -3.83693286e-03, 0.00000000e+00],
    [4.50093997e-03,  3.83476309e-03,  9.99982536e-01, 0.00000000e+00],
    [0.00000000e+00,  0.00000000e+00,  0.00000000e+00, 1.00000000e+00]
])

# 2. R (회전 행렬)과 t (변환 벡터) 추출
R = extrinsic[:3, :3]  # 회전 행렬
t = extrinsic[:3, 3]   # 변환 벡터

# 3. 카메라 위치 (eye), 바라보는 방향 (center), 위쪽 방향 (up) 계산
eye = -R.T @ t
center = eye + R[:, 2]
up = -R[:, 1]

print("Eye (Camera Position):", eye)
print("Center (Look At):", center)
print("Up (Up Direction):", up)

# 4. 메쉬 로드
mesh = o3d.io.read_triangle_mesh("/home/airlabs/Dataset/DTU/dtu_4/scan82/dust3r_test/ply/poisson_mesh_depth_10.ply")  # 메쉬 파일 경로
mesh.compute_vertex_normals()  # 법선 계산 (필수는 아님)

# 5. Open3D 렌더러 생성
width, height = 640, 480  # 렌더링 해상도 설정
renderer = o3d.visualization.rendering.OffscreenRenderer(width, height)

# 메쉬 추가
material = o3d.visualization.rendering.MaterialRecord()
renderer.scene.add_geometry("mesh", mesh, material)

# 카메라 설정
renderer.scene.camera.look_at(center=center, eye=eye, up=up)

# 6. Depth Map 생성
depth_image = renderer.render_to_depth_image()
o3d.io.write_image("depth_map.png", depth_image)  # Depth Map 저장

# Depth Map 시각화 및 확인
depth_array = np.asarray(depth_image)
print("Depth Map Shape:", depth_array.shape)
print("Depth Map (Sample):", depth_array)

# Depth Map을 OpenCV로 시각화 (선택적)
try:
    import cv2
    depth_normalized = cv2.normalize(depth_array, None, 0, 255, cv2.NORM_MINMAX, dtype=cv2.CV_8U)
    cv2.imshow("Depth Map", depth_normalized)
    cv2.waitKey(0)
    cv2.destroyAllWindows()
except ImportError:
    print("OpenCV가 설치되어 있지 않아 Depth Map 시각화를 생략합니다.")


Jupyter environment detected. Enabling Open3D WebVisualizer.
[Open3D INFO] WebRTC GUI backend enabled.
[Open3D INFO] WebRTCWindowSystem: HTTP handshake server disabled.
Eye (Camera Position): [0. 0. 0.]
Center (Look At): [-0.00449909 -0.00383693  0.99998254]
Up (Up Direction): [ 4.90776873e-04 -9.99992554e-01 -3.83476309e-03]
[Open3D INFO] EGL headless mode enabled.
FEngine (64 bits) created at 0x43249930 (threading is enabled)
EGL(1.5)
OpenGL(4.1)
Depth Map Shape: (480, 640)
Depth Map (Sample): [[1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 ...
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]]


QObject::moveToThread: Current thread (0x7f863d8beed0) is not the object's thread (0x7f863d9784e0).
Cannot move to target thread (0x7f863d8beed0)

QObject::moveToThread: Current thread (0x7f863d8beed0) is not the object's thread (0x7f863d9784e0).
Cannot move to target thread (0x7f863d8beed0)

QObject::moveToThread: Current thread (0x7f863d8beed0) is not the object's thread (0x7f863d9784e0).
Cannot move to target thread (0x7f863d8beed0)

QObject::moveToThread: Current thread (0x7f863d8beed0) is not the object's thread (0x7f863d9784e0).
Cannot move to target thread (0x7f863d8beed0)

QObject::moveToThread: Current thread (0x7f863d8beed0) is not the object's thread (0x7f863d9784e0).
Cannot move to target thread (0x7f863d8beed0)

QObject::moveToThread: Current thread (0x7f863d8beed0) is not the object's thread (0x7f863d9784e0).
Cannot move to target thread (0x7f863d8beed0)

QObject::moveToThread: Current thread (0x7f863d8beed0) is not the object's thread (0x7f863d9784e0).
Cannot move to tar